#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Tower,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(150)
#include "VEX_Competition_Includes.c"
void pre_auton (){
}
task autonomous () {
		motor[FR]=-100;
		motor[BR]=-100;
		motor[FL]=100;
		motor[BL]=100;
		wait1Msec(4000);
		motor[FR]=0;
		motor[BR]=0;
		motor[FL]=0;
		motor[BL]=0;
}
task usercontrol(){
	while (1==1){
		//Right joystick controls right wheels
		motor[FR] = -vexRT[Ch2]*(0.65);
		motor[BR]  = -vexRT[Ch2]*(0.65);
		//Left joystick controls left wheels
		motor[FL] = vexRT[Ch3]*(0.65);
		motor[BL]  = vexRT[Ch3]*(0.65);

		//Above, we mutiplied the above values by 0.65 to reduce the power going to the motors by 35% in order to reduce overheating

		//Lift controlled by buttons 6U and 6D
		if(vexRT[Btn6D]){
			motor[RightLift] = 100;
			motor[LeftLift] = 100;
			wait1Msec(1);
			motor[RightLift] = 0;
			motor[LeftLift] = 0;
		}
		if(vexRT[Btn6U]){
			motor[RightLift] = -100;
			motor[LeftLift] = -100;
			wait1Msec(1);
			motor[RightLift] = 0;
			motor[LeftLift] = 0;
		}
		//Tower controlled by buttons 5U and 5D
		if(vexRT[Btn5D]){
			motor[Tower] = -100;
			motor[Tower] = -100;
			wait1Msec(1);
			motor[Tower] = 0;
			motor[Tower] = 0;
		}
		if(vexRT[Btn5U]){
			motor[Tower] = 100;
			motor[Tower] = 100;
			wait1Msec(1);
			motor[Tower] = 0;
			motor[Tower] = 0;
		}
		if(vexRT[Btn8D]){
			startTask(autonomous);
			wait1Msec(15000);
			stopTask(autonomous);
		}
		/* press the bottom button of the right buttons to
		start the autonomous*/
	}
}
